server:
  port: 0 # Usamos puerto aleatorio para que no choquen entre sí

spring:
  application:
    name: asignaturas-servicio
  datasource:
    url: jdbc:mysql://localhost:3307/db_asignaturas
    username: root
    password: Arauca2024**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true
