version: '3.8'

services:

  asignaturas_mysql:
    image: mysql:8.0.30
    container_name: asignaturas_mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Arauca2024**
      MYSQL_DATABASE: db_asignaturas
    ports:
      - "3307:3306"
    volumes:
      - asignaturas_mysql_data:/var/lib/mysql

  matriculas_mysql:
    image: mysql:8.0.30
    container_name: matriculas_mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Arauca2024**
      MYSQL_DATABASE: db_matriculas
    ports:
      - "3308:3306"
    volumes:
      - matriculas_mysql_data:/var/lib/mysql

  usuarios_mysql:
    image: mysql:8.0.30
    container_name: usuarios_mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Arauca2024**
      MYSQL_DATABASE: db_usuarios
    ports:
      - "3309:3306"
    volumes:
      - usuarios_mysql_data:/var/lib/mysql

  servicio_usuarios:
    build:
      context: ./usuarios-servicio
      dockerfile: Dockerfile
    container_name: servicio_usuarios
    ports:
      - "9083:9083"
    depends_on:
      - usuarios_mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://usuarios_mysql:3306/db_usuarios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Arauca2024**

  servicio_asignaturas:
    build:
      context: ./asignaturas-servicio
      dockerfile: Dockerfile
    container_name: servicio_asignaturas
    ports:
      - "9081:9081"
    depends_on:
      - asignaturas_mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://asignaturas_mysql:3306/db_asignaturas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Arauca2024**

  servicio_matriculas:
    build:
      context: ./matriculas-servicio
      dockerfile: Dockerfile
    container_name: servicio_matriculas
    ports:
      - "9082:9082"
    depends_on:
      - matriculas_mysql
      - servicio_usuarios
      - servicio_asignaturas
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://matriculas_mysql:3306/db_matriculas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Arauca2024**



  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka_server
    ports:
      - "9080:9080"

  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config_server
    ports:
      - "9888:9888"

volumes:
  asignaturas_mysql_data:
  matriculas_mysql_data:
  usuarios_mysql_data: