server:
  port: 8082

spring:
  application:
    name: matriculas-servicio
  datasource:
    url: jdbc:mysql://localhost:3308/db_matriculas
    username: root
    password: Arauca2024**
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: claveSuperSecretaParaFirmarTokensJWT123456789
