server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cristiian18/sistema-educativo-microservicios-Cristian
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
